Repository DDAZZA/renogen, pull requests merged in 2020-07, with the labels that each got.

#16 Adds support for validating default headings with allowed values.
  CHANGELOG.md
  README.md
  lib/renogen/change_log.rb
  lib/renogen/change_log/item.rb
  lib/renogen/change_log/validator.rb
  lib/renogen/cli.rb
  lib/renogen/config.rb
  lib/renogen/exceptions.rb
  lib/renogen/exceptions/invalid_item_found.rb
  lib/renogen/formatters/base.rb
  lib/renogen/generator.rb
  lib/renogen/version.rb
  renogen.gemspec
  spec/lib/renogen/change_log/validator_spec.rb
  spec/lib/renogen/config_spec.rb
  spec/lib/renogen/exceptions/invalid_item_found_spec.rb
  spec/lib/renogen/exceptions/stratagy_not_found_spec.rb
Labels: enhancement

#19 Handle invalid yaml files.
  CHANGELOG.md
  lib/renogen/cli.rb
  lib/renogen/exceptions.rb
  lib/renogen/exceptions/yaml_file_blank.rb
  lib/renogen/exceptions/yaml_file_invalid.rb
  lib/renogen/extraction_stratagies.rb
  lib/renogen/extraction_stratagies/yaml_file.rb
  lib/renogen/extraction_stratagies/yaml_file/exceptions.rb
  lib/renogen/extraction_stratagies/yaml_file/exceptions/yaml_file_blank.rb
  lib/renogen/extraction_stratagies/yaml_file/reader.rb
  spec/lib/renogen/exceptions/yaml_file_blank_spec.rb
  spec/lib/renogen/exceptions/yaml_file_invalid_spec.rb
  spec/lib/renogen/extraction_stratagies/yaml_file/reader_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#22 Adds test for writer output for each formatter
  lib/renogen/formatters/csv.rb
  lib/renogen/formatters/markdown_table.rb
  spec/lib/renogen/change_log/writer_spec.rb
Labels: bug

#23 [ISSUE-6] adds config option to strip duplicate entries on non-table output formats
  .renogen
  CHANGELOG.md
  README.md
  lib/renogen/change_log/writer.rb
  lib/renogen/config.rb
  lib/renogen/version.rb
  spec/lib/renogen/change_log/writer_spec.rb
Labels: QA Passed, enhancement
